version: "3.8"
services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./var/www/:/var/www/
  php-fpm:
    build: ./docker/php-fpm
    volumes: 
      - ./var/www/:/var/www/
    working_dir: /var/www/cms
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cake_cms
      MYSQL_USER: cakephp
      MYSQL_PASSWORD: AngelF00dC4k3~
    volumes:
      # DB初期化時に利用 - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./database:/var/lib/mysql
